export interface AnalysisResult {
  risk_score: number;
  confidentiality_score: number;
  red_flags: RedFlag[];
  clause_explanations: ClauseExplanation[];
  profit_suggestions: string[];
  summary: string;
  legal_compliance_notes: string[];
  legal_disclaimer: string;
}

export interface RedFlag {
  clause: string;
  severity: "high" | "medium" | "low";
  explanation: string;
}

export interface ClauseExplanation {
  title: string;
  original_text: string;
  explanation: string;
  risk_level: "high" | "medium" | "low";
}

export const mockAnalysis: AnalysisResult = {
  risk_score: 72,
  confidentiality_score: 45,
  red_flags: [
    {
      clause: "Non-Compete Clause (Section 12.3)",
      severity: "high",
      explanation:
        "The non-compete period of 5 years exceeds the typical enforceable limit under Indian Contract Act. Courts generally uphold 1-2 year restrictions.",
    },
    {
      clause: "Indemnification (Section 8.1)",
      severity: "high",
      explanation:
        "Unlimited indemnification clause places disproportionate liability. Consider capping at contract value.",
    },
    {
      clause: "Intellectual Property (Section 6.2)",
      severity: "medium",
      explanation:
        "Broad IP assignment clause may inadvertently transfer pre-existing IP. Recommend explicit carve-out for prior works.",
    },
    {
      clause: "Termination (Section 14.1)",
      severity: "low",
      explanation:
        "Termination for convenience clause has a 15-day notice period, which is shorter than industry standard of 30 days.",
    },
  ],
  clause_explanations: [
    {
      title: "Force Majeure",
      original_text: "Neither party shall be liable for delays caused by events beyond reasonable control...",
      explanation:
        "This clause is standard and protects both parties from liability during unforeseeable events like natural disasters or pandemics. However, it does not explicitly mention government-ordered lockdowns.",
      risk_level: "low",
    },
    {
      title: "Limitation of Liability",
      original_text: "The total aggregate liability shall not exceed the fees paid in the 12 months preceding the claim...",
      explanation:
        "This cap is reasonable and industry-standard. However, it applies to ALL liability including data breaches, which may need separate treatment under the IT Act, 2000.",
      risk_level: "medium",
    },
    {
      title: "Governing Law",
      original_text: "This agreement shall be governed by the laws of the Republic of India...",
      explanation:
        "Standard governing law clause. Arbitration in Mumbai under the Arbitration and Conciliation Act, 1996 is specified, which is favorable for Indian parties.",
      risk_level: "low",
    },
  ],
  profit_suggestions: [
    "Negotiate a revenue-sharing model instead of flat fees for service agreements exceeding ₹50L.",
    "Add a performance bonus clause tied to KPIs to incentivize delivery quality.",
    "Include an annual rate escalation clause (5-8%) to protect against inflation.",
    "Consider milestone-based payments instead of monthly retainers for project-based work.",
  ],
  summary:
    "This service agreement presents moderate-to-high risk primarily due to an overly broad non-compete clause and unlimited indemnification obligations. The confidentiality provisions are below standard and should be strengthened. The IP assignment clause needs refinement to protect pre-existing intellectual property. Overall, the contract favors the client disproportionately and requires negotiation on 4 key clauses before execution.",
  legal_compliance_notes: [
    "Non-compete clause may be unenforceable under Section 27 of the Indian Contract Act, 1872.",
    "Data protection obligations should reference the Digital Personal Data Protection Act, 2023.",
    "Stamp duty requirements under the Indian Stamp Act, 1899 must be verified for the contract value.",
    "GST implications on service fees should be explicitly addressed per CGST Act, 2017.",
  ],
  legal_disclaimer:
    "This analysis is generated by AI and does not constitute legal advice. It is intended for informational purposes only. Please consult a qualified legal professional before making any decisions based on this analysis. VeriClause AI and its creators are not liable for any actions taken based on this report.",
};

export function simulateAnalysis(): Promise<AnalysisResult> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(mockAnalysis), 3000);
  });
}
