import { useRef, useState } from "react";
import OverallRiskCard from "./OverallRiskCard";
import QuickActions from "./QuickActions";
import RiskDistribution from "./RiskDistribution";
import ContractSummary from "./ContractSummary";
import DetailedRiskAnalysis from "./DetailedRiskAnalysis";
import SuggestedClauses from "./SuggestedClauses";
import RedFlagsList from "./RedFlagsList";
import ScoreCard from "./ScoreCard";
import ContractChat from "./ContractChat";
import GenerateUpdatedContract from "./GenerateUpdatedContract";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Info, Lightbulb, Scale, Download, Trash2, ArrowLeft, Copy, Check, FileText, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import type { AnalysisResult } from "@/lib/mock-analysis";
import { motion } from "framer-motion";
import { useToast } from "@/hooks/use-toast";

interface AnalysisResultsProps {
  result: AnalysisResult;
  onDelete: () => void;
  onCompare: () => void;
  onReanalyze?: () => void;
  isReanalyzing?: boolean;
  contractText?: string;
}

function buildSummaryText(result: AnalysisResult): string {
  const riskLevel = (result.overall_risk_level || "medium").toUpperCase();
  const lines: string[] = [
    "VeriClause AI — Contract Analysis Summary",
    "═".repeat(44),
    "",
    `Risk Level: ${riskLevel}  |  Risk Score: ${result.risk_score}/100  |  Confidentiality: ${result.confidentiality_score}/100`,
    "",
  ];

  if (result.contract_purpose) {
    lines.push(`Purpose: ${result.contract_purpose}`, "");
  }

  if (result.parties?.length) {
    lines.push("Parties:");
    result.parties.forEach((p) => lines.push(`  • ${p.name} — ${p.role} (${p.location})`));
    lines.push("");
  }

  lines.push("Summary:", result.summary, "");

  if (result.red_flags?.length) {
    lines.push(`Red Flags (${result.red_flags.length}):`);
    result.red_flags.forEach((f) =>
      lines.push(`  [${f.severity.toUpperCase()}] ${f.clause}: ${f.explanation}`)
    );
    lines.push("");
  }

  if (result.risk_categories?.length) {
    lines.push("Risk Categories:");
    result.risk_categories.forEach((c) =>
      lines.push(`  • ${c.name}: ${c.level.toUpperCase()} (${c.score}/100)`)
    );
    lines.push("");
  }

  if (result.profit_suggestions?.length) {
    lines.push("Profit Suggestions:");
    result.profit_suggestions.forEach((s, i) => lines.push(`  ${i + 1}. ${s}`));
    lines.push("");
  }

  lines.push("— Generated by VeriClause AI. Not legal advice.");
  return lines.join("\n");
}

const AnalysisResults = ({ result, onDelete, onCompare, onReanalyze, isReanalyzing, contractText }: AnalysisResultsProps) => {
  const { toast } = useToast();
  const reportRef = useRef<HTMLDivElement>(null);
  const [exporting, setExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleExportPdf = async () => {
    if (!reportRef.current) return;
    setExporting(true);
    try {
      const html2canvas = (await import("html2canvas-pro")).default;
      const { jsPDF } = await import("jspdf");

      const canvas = await html2canvas(reportRef.current, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#0b1120",
      });

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF({
        orientation: "portrait",
        unit: "px",
        format: [canvas.width, canvas.height],
      });
      pdf.addImage(imgData, "PNG", 0, 0, canvas.width, canvas.height);
      pdf.save("vericlause-analysis.pdf");
      toast({ title: "PDF Exported", description: "Your analysis report has been downloaded as PDF." });
    } catch (err) {
      console.error("PDF export error:", err);
      toast({ title: "Export Failed", description: "Could not generate PDF. Please try again.", variant: "destructive" });
    } finally {
      setExporting(false);
    }
  };

  const handleCopySummary = () => {
    const text = buildSummaryText(result);
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast({ title: "Copied!", description: "Summary copied to clipboard. Paste it into an email or message." });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      {/* Header */}
      <div className="flex items-start justify-between mb-6 flex-wrap gap-4">
        <div>
          <button
            onClick={onDelete}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-2 transition-colors"
          >
            <ArrowLeft className="h-4 w-4" /> Back to Upload
          </button>
          <h1 className="font-display text-2xl font-bold">Contract Analysis</h1>
          <p className="text-sm text-muted-foreground">Comprehensive AI Risk Analysis</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleCopySummary}>
            {copied ? <Check className="h-4 w-4 mr-1.5" /> : <Copy className="h-4 w-4 mr-1.5" />}
            {copied ? "Copied" : "Copy Summary"}
          </Button>
          <Button variant="outline" size="sm" onClick={handleExportPdf} disabled={exporting}>
            {exporting ? <Loader2 className="h-4 w-4 mr-1.5 animate-spin" /> : <FileText className="h-4 w-4 mr-1.5" />}
            {exporting ? "Generating..." : "Export PDF"}
          </Button>
        </div>
      </div>

      {/* Disclaimer */}
      <Alert className="border-warning/30 bg-warning/5 mb-6">
        <Info className="h-4 w-4 text-warning" />
        <AlertDescription className="text-xs text-muted-foreground">
          {result.legal_disclaimer}
        </AlertDescription>
      </Alert>

      {/* Two-column layout */}
      <div className="grid grid-cols-1 lg:grid-cols-[1fr_300px] gap-6">
        {/* Main content — wrapped in ref for PDF capture */}
        <div className="space-y-6" ref={reportRef}>
          <OverallRiskCard
            riskScore={result.risk_score}
            riskLevel={result.overall_risk_level || (result.risk_score >= 70 ? "high" : result.risk_score >= 40 ? "medium" : "low")}
          />

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <ScoreCard
              label="Risk Score"
              score={result.risk_score}
              description="Higher = more risky. Based on clause severity and legal compliance."
              variant="risk"
            />
            <ScoreCard
              label="Confidentiality Score"
              score={result.confidentiality_score}
              description="Higher = better protected. Measures NDA strength and data clauses."
              variant="confidentiality"
            />
          </div>

          {result.contract_purpose && (
            <ContractSummary
              purpose={result.contract_purpose}
              parties={result.parties || []}
            />
          )}

          <div className="glass rounded-xl p-6">
            <h3 className="font-display text-lg font-semibold mb-3">Summary</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">{result.summary}</p>
          </div>

          {result.risk_categories && result.risk_categories.length > 0 && (
            <DetailedRiskAnalysis categories={result.risk_categories} />
          )}

          {(result.red_flags ?? []).length > 0 && <RedFlagsList flags={result.red_flags} />}

          {result.suggested_clauses && result.suggested_clauses.length > 0 && (
            <SuggestedClauses clauses={result.suggested_clauses} />
          )}

          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Lightbulb className="h-5 w-5 text-warning" />
              <h3 className="font-display text-lg font-semibold">Profit Suggestions</h3>
            </div>
            <ul className="space-y-2">
              {(result.profit_suggestions ?? []).map((s, i) => (
                <li key={i} className="flex items-start gap-3 text-sm text-muted-foreground">
                  <Badge variant="outline" className="shrink-0 mt-0.5 text-xs bg-primary/10 text-primary border-primary/20">
                    {i + 1}
                  </Badge>
                  <span className="leading-relaxed">{s}</span>
                </li>
              ))}
            </ul>
          </div>

          <div className="glass rounded-xl p-6">
            <div className="flex items-center gap-2 mb-4">
              <Scale className="h-5 w-5 text-primary" />
              <h3 className="font-display text-lg font-semibold">Legal Compliance Notes</h3>
            </div>
            <ul className="space-y-2">
              {(result.legal_compliance_notes ?? []).map((note, i) => (
                <li key={i} className="text-sm text-muted-foreground flex items-start gap-2">
                  <span className="text-primary mt-1">•</span>
                  <span className="leading-relaxed">{note}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Sidebar */}
        <div className="space-y-4">
          <QuickActions onNewAnalysis={onDelete} onCompare={onCompare} onReanalyze={onReanalyze} isReanalyzing={isReanalyzing} />
          {result.risk_categories && result.risk_categories.length > 0 && (
            <RiskDistribution categories={result.risk_categories} />
          )}
        </div>
      </div>

      {/* Contract Chat */}
      {/* Generate Updated Contract */}
      {contractText && <GenerateUpdatedContract result={result} contractText={contractText} />}

      {/* Contract Chat */}
      {contractText && <ContractChat contractText={contractText} />}

      {/* Delete */}
      <div className="flex justify-end mt-6">
        <Button variant="destructive" size="sm" onClick={onDelete}>
          <Trash2 className="h-4 w-4 mr-1" /> Delete Analysis
        </Button>
      </div>
    </motion.div>
  );
};

export default AnalysisResults;
